plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.drivehub.mgha'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.drivehub.mgha"
        minSdk 28
        targetSdk 36
        versionCode 6
        versionName "1.7.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    flavorDimensions "device"
    productFlavors {
        sim {
            dimension "device"
            applicationId "com.drivehub.mgha.sim"
        }
        car {
            dimension "device"
            applicationId "com.drivehub.mgha"
        }
    }

    buildTypes {
        debug {
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        buildConfig true
    }
    lint {
        lintConfig = file("lint.xml")
    }
}

dependencies {
    implementation libs.core
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
